### ISSUE TITLE
documentTags.tv

### ISSUE THREAD

**Issue by risingisland** [Nicola1971/Doclister-Tags-in-Ditto-Style#2]
I dont believe the "documentTags" TV is included in the default install.
Should that be included for people who are not upgrading?

**Comment by Nicola1971** [comment]
you are right. Is not explained :)

feel free to fork and pull any fix to the readme documentation - my english is not very good :smile:

**Comment by risingisland** [comment]
Forked and Pull created. 
Will review readme and test soon.
